package com.dental.clinic.management.warehouse.dto.request;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/**
 * API 6.4: Enhanced Import Transaction Request
 *
 * Features:
 * - Invoice number for accounting reconciliation
 * - Expected delivery date for supplier KPI
 * - Purchase price for COGS calculation
 * - Unit selection for proper conversion
 * - Bin location for warehouse organization
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ImportTransactionRequest {

    @NotNull(message = "Mã nhà cung cấp là bắt buộc")
    @Positive(message = "Mã nhà cung cấp phải là số dương")
    private Long supplierId;

    @NotNull(message = "Ngày giao dịch là bắt buộc")
    private LocalDate transactionDate;

    // ❌ REMOVED: invoiceNumber - Now auto-generated by BE in format: INV-YYYY-XXX
    // @NotBlank(message = "Số hóa đơn là bắt buộc")
    // @Size(max = 100, message = "Số hóa đơn không được vượt quá 100 ký tự")
    // private String invoiceNumber;

    private LocalDate expectedDeliveryDate;

    @Size(max = 500, message = "Ghi chú không được vượt quá 500 ký tự")
    private String notes;

    @NotEmpty(message = "Danh sách vật tư không được để trống")
    @Valid
    private List<ImportItemRequest> items;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class ImportItemRequest {

        @NotNull(message = "Mã vật tư chính là bắt buộc")
        @Positive(message = "Mã vật tư chính phải là số dương")
        private Long itemMasterId;

        @NotBlank(message = "Số lô là bắt buộc")
        @Size(max = 100, message = "Số lô không được vượt quá 100 ký tự")
        private String lotNumber;

        @NotNull(message = "Ngày hết hạn là bắt buộc")
        private LocalDate expiryDate;

        @NotNull(message = "Số lượng là bắt buộc")
        @Positive(message = "Số lượng phải lớn hơn 0")
        @Max(value = 1000000, message = "Số lượng không được vượt quá 1.000.000 đơn vị")
        private Integer quantity;

        @NotNull(message = "Mã đơn vị là bắt buộc")
        @Positive(message = "Mã đơn vị phải là số dương")
        private Long unitId;

        @NotNull(message = "Giá mua là bắt buộc")
        @DecimalMin(value = "0.01", message = "Giá mua phải lớn hơn 0")
        @DecimalMax(value = "100000000.00", message = "Giá mua không được vượt quá 100.000.000 VNĐ")
        private BigDecimal purchasePrice;

        @Size(max = 200, message = "Vị trí kho không được vượt quá 200 ký tự")
        private String binLocation;

        @Size(max = 500, message = "Ghi chú không được vượt quá 500 ký tự")
        private String notes;
    }
}
