[phases.setup]
nixPkgs = ['...', 'jdk17']

[phases.build]
cmds = [
    'chmod +x mvnw',
    './mvnw clean package -DskipTests'
]

[start]
cmd = 'java -Dserver.port=$PORT $JAVA_OPTS -jar target/*.jar'
