package com.dental.clinic.management.notification.enums;

public enum NotificationType {
    APPOINTMENT_CREATED,
    APPOINTMENT_UPDATED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REMINDER,
    APPOINTMENT_COMPLETED,
    TREATMENT_PLAN_APPROVED,
    TREATMENT_PLAN_UPDATED,
    PAYMENT_RECEIVED,
    SYSTEM_ANNOUNCEMENT,
    REQUEST_TIME_OFF_PENDING,
    REQUEST_OVERTIME_PENDING,
    REQUEST_PART_TIME_PENDING
}
